import { createClient } from '@supabase/supabase-js';

// Define the structure for your database tables (optional but recommended)
export interface MessageHistory {
  id?: number; // Auto-generated by Supabase
  created_at?: string; // Auto-generated by Supabase
  role: 'user' | 'bot';
  content: string;
}

// Define Database interface
export interface Database {
  public: {
    Tables: {
      message_history: {
        Row: MessageHistory; // The data expected from SELECT
        Insert: MessageHistory; // The data expected for INSERT
        Update: Partial<MessageHistory>; // The data expected for UPDATE
      };
    };
    Views: {
      // Add views if needed
    };
    Functions: {
      // Add functions if needed
    };
  };
}


const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error('Missing environment variable NEXT_PUBLIC_SUPABASE_URL');
}
if (!supabaseAnonKey) {
  throw new Error('Missing environment variable NEXT_PUBLIC_SUPABASE_ANON_KEY');
}

// Initialize the Supabase client
// Pass the Database generic for type safety
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
