import { createClient } from '@supabase/supabase-js';

// Define the structure for your database tables (optional but recommended)
// Match the column names and types from your Supabase table definition
export interface MessageHistory {
  id: number; // Corresponds to bigint or int8, primary key
  created_at: string; // Corresponds to timestamptz
  role: 'user' | 'bot'; // Corresponds to text with constraint
  content: string; // Corresponds to text
}

// Define Database interface
// This helps TypeScript understand your Supabase schema
export interface Database {
  public: {
    Tables: {
      message_history: {
        Row: MessageHistory; // The data expected from SELECT
        // For Insert, omit fields that are auto-generated by the database (id, created_at)
        Insert: Omit<MessageHistory, 'id' | 'created_at'>;
        // For Update, make fields optional
        Update: Partial<Omit<MessageHistory, 'id' | 'created_at'>>;
      };
    };
    Views: {
      // Add views if needed
    };
    Functions: {
      // Add functions if needed
    };
  };
}


const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://rxahcmtrbndxoqmhwzpl.supabase.co';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWhjbXRyYm5keG9xbWh3enBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzUwMjEsImV4cCI6MjA2MTQxMTAyMX0.bDhDF6CChWoGKppMmLZlg3eQUCvE9_pNQPYN4oJz6Bw';

// Helper function to validate URL format (moved before usage)
function isValidUrl(string: string | undefined): string is string {
  if (!string) return false;
  try {
    new URL(string);
    return true;
  } catch (_) {
    return false;
  }
}

let supabaseInstance = null;

if (!supabaseUrl) {
  console.error('Missing environment variable NEXT_PUBLIC_SUPABASE_URL');
} else if (!isValidUrl(supabaseUrl)) {
    console.error(`Invalid URL in NEXT_PUBLIC_SUPABASE_URL: "${supabaseUrl}"`);
} else if (!supabaseAnonKey) {
  console.error('Missing environment variable NEXT_PUBLIC_SUPABASE_ANON_KEY');
} else {
  try {
    // Initialize the Supabase client ONLY if URL and Key are valid
    // Pass the Database generic for type safety
    supabaseInstance = createClient<Database>(supabaseUrl, supabaseAnonKey);
    console.log("Supabase client initialized successfully.");
  } catch (error: any) {
      console.error('Error initializing Supabase client:', error.message);
  }
}

// Export the potentially null instance
export const supabase = supabaseInstance;

if (!supabase) {
  console.error('Supabase client could not be initialized. Check environment variables and URL format.');
}
