import { createClient } from '@supabase/supabase-js';

// Define the structure for your database tables (optional but recommended)
export interface MessageHistory {
  id?: number; // Auto-generated by Supabase
  created_at?: string; // Auto-generated by Supabase
  role: 'user' | 'bot';
  content: string;
}

// Define Database interface
export interface Database {
  public: {
    Tables: {
      message_history: {
        Row: MessageHistory; // The data expected from SELECT
        Insert: MessageHistory; // The data expected for INSERT
        Update: Partial<MessageHistory>; // The data expected for UPDATE
      };
    };
    Views: {
      // Add views if needed
    };
    Functions: {
      // Add functions if needed
    };
  };
}


const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://rxahcmtrbndxoqmhwzpl.supabase.co';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWhjbXRyYm5keG9xbWh3enBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzUwMjEsImV4cCI6MjA2MTQxMTAyMX0.bDhDF6CChWoGKppMmLZlg3eQUCvE9_pNQPYN4oJz6Bw';

if (!supabaseUrl) {
  console.error('Missing environment variable NEXT_PUBLIC_SUPABASE_URL');
}

if (!isValidUrl(supabaseUrl)) {
  console.error('Invalid URL in NEXT_PUBLIC_SUPABASE_URL');
}

if (!supabaseAnonKey) {
  console.error('Missing environment variable NEXT_PUBLIC_SUPABASE_ANON_KEY');
}

// Helper function to validate URL format
function isValidUrl(string: string) {
  try {
    new URL(string);
    return true;
  } catch (_) {
    return false;
  }
}


// Initialize the Supabase client
// Pass the Database generic for type safety
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
