'use server';

import { supabase } from '@/lib/supabase-client';
import { z } from 'zod';

// --- Types and Schemas ---

// Simple schema for a single message to be saved
const SaveMessageSchema = z.object({
  role: z.enum(['user', 'bot']),
  content: z.string().min(1),
});

// Define the return type for fetching messages
// Use the MessageHistory type defined in supabase-client.ts
import type { MessageHistory } from '@/lib/supabase-client';
interface FetchHistoryResult {
  success: boolean;
  data: MessageHistory[];
  error?: string;
}

// Define the return type for saving a message
interface SaveMessageResult {
  success: boolean;
  error?: string;
}


// --- Server Actions ---

/**
 * Fetches chat history from the 'message_history' table in Supabase.
 * Orders messages by creation time (oldest first).
 */
export async function fetchChatHistory(): Promise<FetchHistoryResult> {
  console.log('[fetchChatHistory] Attempting to fetch chat history...');
  // Use the standard Supabase client initialized with the anon key
  if (!supabase) {
      console.error('[fetchChatHistory] Supabase client is not initialized.');
      return { success: false, data: [], error: 'Supabase client not initialized.' };
  }
  try {
    // Select only the columns defined in MessageHistory for type safety
    const { data, error } = await supabase
      .from('message_history')
      .select('id, created_at, role, content') // Explicitly select columns
      .order('created_at', { ascending: true }); // Order by timestamp ASC

    if (error) {
      console.error('[fetchChatHistory] Supabase error:', error);
      // Check specifically for RLS errors
      if (error.message.includes('relation "public.message_history" does not exist') || error.message.includes('Could not find the specified table')) {
           console.error('[fetchChatHistory] Table "message_history" might not exist. Check Supabase table editor.');
           return { success: false, data: [], error: 'Table not found.' };
      } else if (error.message.includes('security policy') || error.code === '42501') { // 42501 is permission denied
           console.error('[fetchChatHistory] RLS policy might be preventing reads. Check Supabase Authentication > Policies for message_history (SELECT). Public read access is needed.');
           return { success: false, data: [], error: 'Permission denied. Check RLS policies for read access.' };
      }
      return { success: false, data: [], error: error.message };
    }

    console.log(`[fetchChatHistory] Successfully fetched ${data?.length ?? 0} messages.`);
    // Ensure data is not null before returning
    // Cast the data to MessageHistory[] to ensure type consistency
    const messages: MessageHistory[] = data?.map((item: any) => ({
        id: item.id,
        created_at: item.created_at,
        // Ensure role matches the enum - convert 'model' to 'bot' if found
        role: item.role === 'model' ? 'bot' : (item.role as 'user' | 'bot'), 
        content: item.content,
    })) ?? [];
    return { success: true, data: messages };

  } catch (err: any) {
    console.error('[fetchChatHistory] Unexpected error:', err);
    return { success: false, data: [], error: err.message || 'An unknown error occurred.' };
  }
}

/**
 * Saves a single chat message to the 'message_history' table in Supabase.
 */
export async function saveChatMessage(
  input: z.infer<typeof SaveMessageSchema>
): Promise<SaveMessageResult> {
  console.log('[saveChatMessage] Attempting to save message:', { role: input.role, content: input.content.substring(0, 50) + '...' });
   // Use the standard Supabase client initialized with the anon key
  if (!supabase) {
    console.error('[saveChatMessage] Supabase client is not initialized.');
    return { success: false, error: 'Supabase client not initialized.' };
   }

  // Validate input
  const validationResult = SaveMessageSchema.safeParse(input);
  if (!validationResult.success) {
    console.error('[saveChatMessage] Invalid input:', validationResult.error);
    return { success: false, error: 'Invalid message data.' };
  }

  const { role, content } = validationResult.data;

  try {
    console.log('[saveChatMessage] Preparing to insert into Supabase:', { role, content: content.substring(0, 50) + '...' });
    // Ensure the inserted object matches the expected table structure (id and created_at are generated by DB)
    const { error } = await supabase
      .from('message_history')
      .insert([{ role, content }]); // Insert the validated data

    if (error) {
      console.error('[saveChatMessage] Supabase insert error:', error);
       // Check specifically for RLS errors during insert
       if (error.message.includes('security policy') || error.code === '42501') { // 42501 is permission denied
           console.error('[saveChatMessage] RLS policy prevented insert. Check Supabase Authentication > Policies for message_history (INSERT). Ensure it allows public role for development if not using Supabase Auth.');
           return { success: false, error: 'Permission denied. Check RLS policies for insert access.' };
       } else if (error.message.includes('relation "public.message_history" does not exist') || error.message.includes('Could not find the specified table')) {
            console.error('[saveChatMessage] Table "message_history" might not exist. Check Supabase table editor.');
            return { success: false, error: 'Table not found.' };
       }
      return { success: false, error: error.message };
    }

    console.log('[saveChatMessage] Message saved successfully to Supabase.');
    return { success: true };
  } catch (err: any) {
    console.error('[saveChatMessage] Unexpected error during insert:', err);
    return { success: false, error: err.message || 'An unknown error occurred.' };
  }
}
